/**
 * Generates the fixture that proves shared/merkle.mjs and RobinhoodAirdrop
 * agree.
 *
 * The point is not that two JavaScript files produce the same number. It is
 * that the root and proofs computed here are handed to the deployed contract
 * bytecode in RobinhoodAirdrop.merkle.t.sol, which then has to accept them. If
 * the two conventions differ anywhere, that test fails and no claim would ever
 * have worked in production.
 *
 * Run: node shared/gen-fixture.mjs
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { buildTree } from "./merkle.mjs";
import { buildList } from "./airdrop-list.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

// A deliberately awkward list: 101 entries so the tree has odd levels and the
// promote-the-lone-node rule is exercised, amounts spanning eight orders of
// magnitude, mixed case, one duplicate to merge and one blank line.
const lines = [];
for (let i = 0; i < 100; i++) {
  const addr = "0x" + (BigInt("0x1000000000000000000000000000000000000000") + BigInt(i * 7919)).toString(16).padStart(40, "0");
  const amount = i % 3 === 0 ? "1" : i % 3 === 1 ? "1234.56789" : "9999999";
  lines.push(`${i % 5 === 0 ? addr.toUpperCase().replace("0X", "0x") : addr}:${amount}`);
}
lines.push("");
lines.push("# a comment the parser must ignore");
lines.push(lines[0]); // duplicate, must merge rather than appear twice
lines.push("0x2000000000000000000000000000000000000abc, 500"); // comma separated

const list = buildList(lines.join("\n"), { decimals: 18 });
if (list.problems.length) {
  console.error("fixture has parse problems:", list.problems);
  process.exit(1);
}

const tree = buildTree(list.entries);

// Prove a spread of positions, including the first, the last and an odd one
// that has to be promoted up a level.
const picks = [0, 1, 7, 50, list.count - 2, list.count - 1];
const claims = picks.map((index) => ({
  index,
  account: list.entries[index].address,
  amount: list.entries[index].amount.toString(),
  proof: tree.proofFor(index),
}));

const out = {
  note: "Generated by shared/gen-fixture.mjs. Consumed by RobinhoodAirdrop.merkle.t.sol.",
  count: list.count,
  merged: list.merged,
  total: list.total.toString(),
  root: tree.root,
  claimCount: claims.length,
  claims,
};

mkdirSync(join(HERE, "..", "contracts", "test", "fixtures"), { recursive: true });
writeFileSync(join(HERE, "..", "contracts", "test", "fixtures", "merkle.json"), JSON.stringify(out, null, 2) + "\n");

console.log(`  entries      ${list.count} (merged ${list.merged} duplicate)`);
console.log(`  total        ${list.total}`);
console.log(`  root         ${tree.root}`);
console.log(`  proofs       ${claims.length} written`);
