import { h2, h3, p, esc, info } from "../components.mjs";

/* Questions are defined once. The visible answers and the FAQPage structured
 * data are both derived from this array, so they can never disagree — which is
 * the whole requirement behind FAQ markup, and the reason to generate rather
 * than hand-write it twice.
 *
 * `a` is the plain-text answer used for structured data. `html` is the same
 * answer with links, used for the page. Keeping the link out of the JSON-LD is
 * deliberate: rich results strip markup anyway.
 */
const GROUPS = [
  ["Getting started", [
    ["What is HoodLock?",
     "HoodLock is a non-custodial token locker, burner and vesting platform on Robinhood Chain. It holds ERC-20 tokens until a date you set, sends tokens permanently to the dead address, or releases them gradually to a beneficiary — and gives every record a public page anyone can verify.",
     'HoodLock is a non-custodial token locker, burner and vesting platform on Robinhood Chain. It holds ERC-20 tokens until a date you set, sends tokens permanently to the dead address, or releases them gradually to a beneficiary — and gives every record a <a href="/docs/proof-of-lock">public page anyone can verify</a>.'],
    ["Do I need an account?",
     "No. There is no sign-up, no email and no password. Connecting a wallet is the only identity involved, and browsing proof pages or the explorer needs no wallet at all.", null],
    ["Which chain does HoodLock run on?",
     "Robinhood Chain only, chain id 4663. It is an Ethereum L2 built on the Arbitrum stack, with ETH as the gas token.",
     'Robinhood Chain only, chain id 4663. It is an Ethereum L2 built on the Arbitrum stack, with ETH as the gas token. Full parameters are on the <a href="/docs/network">network page</a>.'],
    ["Which wallets are supported?",
     "Any wallet that supports Robinhood Chain. Browser extensions are discovered automatically, and WalletConnect covers mobile wallets and anything not installed locally.",
     'Any wallet that supports Robinhood Chain. Browser extensions are discovered automatically, and WalletConnect covers mobile wallets. See <a href="/docs/connect-wallet">connecting a wallet</a>.'],
    ["How long does locking take?",
     "Two transactions and about a minute. The first approves the amount, the second creates the lock.",
     'Two transactions and about a minute. The first approves the amount, the second creates the lock. See the <a href="/docs/quickstart">quickstart</a>.'],
    ["Can I try it with a small amount first?",
     "Yes, and it is a reasonable thing to do. The fee is flat rather than a percentage, so a test lock costs the same as a large one — but nothing stops you locking a token dust balance to see the flow end to end.", null],
  ]],

  ["Costs", [
    ["How much does it cost to lock tokens?",
     "A flat 0.005 ETH per lock, plus gas. No percentage of your tokens is taken at any point.",
     'A flat 0.005 ETH per lock, plus gas. No percentage of your tokens is taken at any point. Full breakdown on the <a href="/docs/fees">fees page</a>.'],
    ["Is there a fee to withdraw?",
     "No. Withdrawing an expired lock costs gas only. The fee is charged once, when the lock is created.", null],
    ["Is there a fee to claim vested tokens?",
     "No. Claiming is free apart from gas. The vesting fee is charged once, at creation.", null],
    ["Does extending a lock cost anything?",
     "No fee, just gas. That is deliberate — extending should be the cheapest option, because it is usually the right one.",
     'No fee, just gas. That is deliberate — extending should be the cheapest option, because it is usually the right one. See <a href="/docs/how-to-extend-a-lock">extending a lock</a>.'],
    ["Do you take a percentage of locked tokens?",
     "No, never, at any stage. The fee is a flat amount in ETH. A locker paid in your token has a reason to prefer larger locks over appropriate ones, which is precisely the incentive a flat fee avoids.", null],
    ["Can the fee change?",
     "Yes, but only for new records. An existing lock or schedule is never re-priced, and withdrawal and claiming stay free regardless.",
     'Yes, but only for new records. An existing lock or schedule is never re-priced. The vesting contract has a hard cap of 0.05 ETH written into the code; the locker and burner do not. See <a href="/docs/fees">fees</a>.'],
    ["What happens if I overpay the fee?",
     "The locker and burner refund the difference automatically. The vesting contract requires the exact fee and reverts on overpayment — it has no refund path.", null],
  ]],

  ["Locking", [
    ["Can locked tokens be withdrawn early?",
     "No. The contract checks the unlock time on every withdrawal and reverts before it. There is no override, no admin path and no exception.",
     'No. The contract checks the unlock time on every withdrawal and reverts before it. There is no override and no admin path — see the <a href="/docs/security">security model</a>.'],
    ["Who owns locked tokens?",
     "You do. The lock records your address as the owner, and only that address can withdraw, and only after the unlock time. HoodLock never gains the ability to move them.", null],
    ["Can the team unlock tokens early?",
     "Not if they are locked with HoodLock. No function exists that shortens a lock or releases it ahead of schedule, so it is not a matter of policy or goodwill.", null],
    ["Can I extend a lock?",
     "Yes, as many times as you like, for free. Unlock dates can always be pushed further out and can never be pulled in.",
     'Yes, as many times as you like, for free. Unlock dates can always be pushed further out and can never be pulled in — see <a href="/docs/how-to-extend-a-lock">extending a lock</a>.'],
    ["Can I shorten a lock?",
     "No. The contract requires any new unlock time to be strictly later than the current one. That asymmetry is what makes an unlock date a commitment rather than a preference.", null],
    ["Can I unlock part of a lock early?",
     "No. A lock is a single record with one amount and one date. If you need staggered access, create several locks with different dates rather than one large one.", null],
    ["Can I add more tokens to an existing lock?",
     "No — create a second lock. Locks are independent records, which also means they can carry different dates.", null],
    ["What happens when a lock expires?",
     "Nothing automatic. The tokens stay in the contract until the owner sends a withdrawal transaction, and they can stay there indefinitely.",
     'Nothing automatic. The tokens stay in the contract until the owner withdraws, and can stay there indefinitely. See <a href="/docs/when-a-lock-expires">when a lock expires</a>.'],
    ["Can I transfer a lock to another wallet?",
     "Yes. Ownership of the lock can be transferred to a new address, which then holds the right to withdraw. The tokens themselves do not move.", null],
    ["What can be locked?",
     "Any ERC-20 on Robinhood Chain: project tokens, treasury balances, creator supply, and v2-style LP tokens, which are themselves ERC-20.",
     'Any ERC-20 on Robinhood Chain, including v2-style LP tokens. Uniswap v3 and v4 positions are NFTs and cannot be locked — see the <a href="/docs/liquidity-locker">liquidity locker</a>.'],
    ["Is there a minimum lock duration?",
     "For locks, no — any time in the future is valid. Vesting schedules must run at least 24 hours.", null],
    ["Is there a maximum lock duration?",
     "No practical maximum. Choose a date you can defend rather than the largest number available.", null],
    ["Do I keep earning staking rewards on locked tokens?",
     "No. Locked tokens sit in the locker contract, so anything that depends on holding them in your own wallet — staking, airdrops, governance — will not see them.", null],
  ]],

  ["Liquidity", [
    ["Can I lock LP tokens?",
     "Yes, if they are v2-style. A Uniswap v2 or SushiSwap v2 position is an ERC-20 token and locks like any other balance.",
     'Yes, if they are v2-style — those positions are ERC-20 tokens. See <a href="/docs/how-to-lock-liquidity">locking LP tokens</a>.'],
    ["Why can't I lock my Uniswap v3 position?",
     "A v3 or v4 liquidity position is an NFT, not an ERC-20 token. The HoodLock locker holds ERC-20s, so it cannot hold one. Many launchpads already lock or burn those positions at graduation.", null],
    ["How do I tell whether my LP is v2 or v3?",
     "A v2 position appears in your wallet as a token balance with a symbol like UNI-V2 or SLP, and its pair contract has a totalSupply function. A v3 position does not appear as a token at all.",
     'A v2 position appears in your wallet as a token balance, usually with a symbol like UNI-V2, and its pair contract has <code>totalSupply()</code>. A v3 position does not appear as a token at all. More in the <a href="/docs/liquidity-locker">liquidity locker</a>.'],
    ["Does locking LP stop the pool from trading?",
     "No. Locking the LP token prevents liquidity being withdrawn. Swaps, fees and price discovery all continue exactly as before.", null],
    ["Should I lock or burn liquidity?",
     "Burning is permanent and needs no trust at all; locking is temporary and keeps the option to migrate the pool later. Neither is strictly better — it depends on whether you may need to move the pool.",
     'Burning is permanent and needs no trust; locking is temporary and keeps the option to migrate. <a href="/blog/burning-vs-locking-liquidity">The comparison</a> covers when each fits.'],
    ["My launchpad already locked the liquidity. Do I need to do anything?",
     "Not for the liquidity. What usually remains is fee revenue, a creator buy from the curve, or a treasury — ordinary balances that a holder looks at once liquidity is settled.", null],
    ["How long should I lock liquidity for?",
     "Long enough to outlast whatever people are worried about, and long enough to cover your first milestone. Because extending is free and shortening is impossible, err short and extend.",
     'Long enough to outlast whatever people are worried about. Because extending is free and shortening is impossible, err short and extend — <a href="/blog/how-long-should-you-lock-liquidity">the full discussion</a>.'],
  ]],

  ["Vesting", [
    ["What is the difference between a lock and vesting?",
     "A lock releases everything on one date. Vesting releases gradually between a start and an end, optionally after a cliff. Locks suit a single allocation you hold; vesting suits supply going to people over time.",
     'A lock releases everything on one date; vesting releases gradually, optionally after a cliff. <a href="/blog/token-locks-vs-vesting-vs-burning">Locks vs vesting vs burning</a> compares them properly.'],
    ["Can a vesting schedule be cancelled?",
     "No. Schedules are irrevocable — there is no revoke, no sweep and no rescue function in the contract. Check the beneficiary and the amount before signing.",
     'No. Schedules are irrevocable: there is no revoke, sweep or rescue function. See <a href="/docs/token-vesting">token vesting</a>.'],
    ["Can I edit a vesting schedule after creating it?",
     "No. Not the amount, not the dates, not the recipient. This is the one action on HoodLock where a mistake cannot be corrected.", null],
    ["What is a cliff?",
     "A date before which nothing is claimable, even though time is accruing. When it passes, everything earned up to that point becomes claimable at once.",
     'A date before which nothing is claimable, even though time is accruing. When it passes, everything earned to that point becomes claimable at once — <a href="/blog/what-is-a-vesting-cliff">why holders look for one</a>.'],
    ["Who can claim vested tokens?",
     "Only the current beneficiary. The creator cannot claim on their behalf and cannot redirect the schedule.", null],
    ["Do unclaimed vested tokens expire?",
     "No. They accumulate and stay claimable indefinitely. There is no deadline and nothing is lost by claiming late.", null],
    ["Can the beneficiary be changed?",
     "Yes, but only by the current beneficiary — for a wallet change or a handover. The creator cannot do it for them.", null],
    ["Can I vest for a whole team at once?",
     "Yes. Batch creation makes one schedule per beneficiary in a single transaction, up to 200, sharing the same token and timing. The fee is charged per schedule.",
     'Yes — up to 200 beneficiaries in one transaction, sharing the same token and timing. See <a href="/docs/how-to-create-vesting">creating a schedule</a>.'],
    ["Can a vesting schedule start in the past?",
     "Yes, and it is legitimate for teams vesting from a date people actually joined. But a schedule that is already half claimable on day one is in practice half a transfer, and the proof page shows that percentage.", null],
    ["Why did my vesting transaction revert?",
     "Most often because the schedule ends less than 24 hours from now, or because the fee was not exact. The vesting contract requires msg.value to equal the fee precisely and does not refund overpayment.",
     'Most often the 24-hour minimum duration, or an inexact fee — vesting requires <code>msg.value == fee</code> exactly. More causes in <a href="/docs/troubleshooting">troubleshooting</a>.'],
  ]],

  ["Burning", [
    ["What does burning actually do?",
     "It transfers tokens from your wallet to the dead address in a single hop and writes a permanent record of the amount, the token and the time.", null],
    ["Can burned tokens be recovered?",
     "No. The dead address has no private key, so there is nobody who could return them — including us. Burning is permanent by construction rather than by policy.",
     'No. The dead address has no private key, so there is nobody who could return them. See <a href="/docs/token-burning">token burning</a>.'],
    ["Why burn through HoodLock instead of sending to the dead address myself?",
     "Both destroy the supply. Only one produces an indexed record and a page stating the amount and share of supply that a reader can check without knowing how to use a block explorer.", null],
    ["Do burned tokens sit in your contract first?",
     "No. The transfer goes straight from your wallet to the dead address. There is no intermediate custody step.", null],
  ]],

  ["Verification and trust", [
    ["How do investors verify a lock?",
     "By opening the proof page, checking the token address matches the token actually trading, reading the share of supply rather than the raw amount, and checking the unlock date.",
     'By opening the proof page, checking the token address matches what is actually trading, reading the share of supply rather than the raw token count, and checking the date. Full method: <a href="/docs/how-to-verify-a-lock">verifying a lock</a>.'],
    ["Can I verify a lock without a wallet?",
     "Yes. Proof pages, token pages and the explorer all work with no wallet and no account.", null],
    ["What is a proof page?",
     "A public URL for a single lock, burn or vesting schedule that renders the current on-chain state — token, amount, share of supply, dates and status — and links to the transaction.",
     'A public URL for a single record that renders current on-chain state and links to the transaction. See <a href="/docs/proof-of-lock">proof of lock</a>.'],
    ["Does a lock mean a token is safe?",
     "No. A lock is evidence about one balance. It says nothing about the token contract, the remaining supply or the team.",
     'No. A lock is evidence about one balance and says nothing about the token contract or the rest of the supply — <a href="/blog/rug-pull-red-flags-checklist">the other checks</a>.'],
    ["Someone showed me a screenshot of a lock. Is that enough?",
     "No. Ask for the link and open it yourself, then confirm the token address on the page matches the token you would actually buy. Symbols repeat; addresses do not.", null],
    ["Can HoodLock take my tokens?",
     "No function exists that would let us. Only the lock owner can withdraw, and only after the unlock time; only the beneficiary can claim. All three contracts are verified, so this is checkable rather than promised.",
     'No function exists that would let us, and all three contracts are verified so you can check rather than trust — <a href="/docs/security">the security model</a> names the exact functions to read.'],
    ["What can the admin do?",
     "Change the fee for new records, change the fee collector, and transfer the admin role. No admin function can touch an existing lock, schedule or balance.", null],
    ["Are the contracts audited?",
     "The contracts are verified on Blockscout, which means the published source is the bytecode that runs, and the vesting contract was built against a written threat model with a full test suite. Verification is not the same as a third-party audit, and we do not claim it is.", null],
    ["What happens if HoodLock disappears?",
     "The contracts keep running. They are deployed on-chain and do not depend on our site — you can call withdraw or claim directly from a block explorer. The proof pages would go, the funds would not.", null],
  ]],

  ["Developers", [
    ["Can I add locking to my own site?",
     "Yes, two ways: an embed widget that is one script tag and a button, or a REST API that returns prepared transactions for you to submit from the user's wallet.",
     'Yes — an <a href="/docs/embed">embed widget</a> that is one script tag, or a <a href="/docs/api">REST API</a> returning prepared transactions.'],
    ["Can I style the button myself?",
     "Yes. The widget attaches a click handler and nothing else — it sets no classes, no inline styles and no attributes affecting appearance. Your button stays entirely yours.", null],
    ["Is the API key secret?",
     "No, it is public by design, in the same sense as a Stripe publishable key. It credits actions to you and cannot move funds, read balances or reach admin. Embedding it in frontend source is the intended use.", null],
    ["How much do partners earn?",
     "50% of the fee on every lock, burn and vesting schedule created by a wallet they introduced, claimable to their own wallet once the balance passes $10.", null],
    ["Can I offer only locking, without burn and vesting?",
     "Yes. Each button is independent — a lock-only integration is a single button with no extra attributes. You earn on whichever products you add.", null],
    ["Do the API endpoints support CORS?",
     "Yes, they send permissive CORS headers and work from a browser. Note that the API key is passed as a query parameter on GET and a body field on POST — there is no header form, because the CORS policy allows Content-Type only.", null],
  ]],
];

const ALL = GROUPS.flatMap(([, qs]) => qs);

const body = GROUPS.map(([title, qs]) =>
  h2(title) + qs.map(([q, a, html]) =>
    h3(q) + p(html || esc(a).replace(/&#39;/g, "'").replace(/&quot;/g, '"')),
  ).join("")).join("");

export default {
  slug: "faq",
  navTitle: "FAQ",
  seoTitle: "HoodLock FAQ | Token Locking on Robinhood Chain, Answered",
  desc: "Answers to the questions people actually ask about locking, burning and vesting tokens on Robinhood Chain — costs, guarantees, verification and limits.",
  updated: "2026-07-29",
  h1: 'Frequently asked <span class="serif">questions.</span>',
  lede: `${ALL.length} questions, grouped by what you are trying to work out. Every answer is on this page — nothing is hidden behind a click.`,
  body: info(`Looking for something specific? Press <code>/</code> to search the documentation, or start
    from the <a href="/docs">documentation home</a>.`) + body,
  faqs: ALL.map(([q, a]) => [q, a]),
  related: [
    { href: "/docs/quickstart", title: "Quickstart" },
    { href: "/docs/security", title: "Security model" },
    { href: "/docs/fees", title: "Fees" },
    { href: "/docs/learn", title: "Learn", note: "longer-form background reading" },
  ],
};
