import { h2, p, ul, table, info, warn, doc, blog } from "../components.mjs";

export default {
  slug: "fees",
  navTitle: "Fees",
  seoTitle: "HoodLock Fees | Flat 0.005 ETH, No Percentage of Your Tokens",
  desc: "One flat ETH fee per lock, burn or vesting schedule on Robinhood Chain. No percentage cut, free withdrawals and free claims, with the caps written into the code.",
  updated: "2026-07-29",
  h1: 'Fees.',
  lede: "One flat fee in ETH, charged once, at creation. No percentage of your tokens is taken at any point, not on the way in, not on the way out.",
  body: `
${h2("What you pay")}
${table(["Action", "Fee", "Charged"], [
  ["Create a lock", "0.005 ETH", "Once, at creation"],
  ["Burn tokens", "0.005 ETH", "Once, at the burn"],
  ["Create a vesting schedule", "0.005 ETH", "Once per schedule, at creation"],
  ["Withdraw an expired lock", "<b>Free</b>", "Gas only"],
  ["Claim vested tokens", "<b>Free</b>", "Gas only"],
  ["Extend a lock", "<b>Free</b>", "Gas only"],
])}
${p(`Gas on Robinhood Chain is paid in ETH and is small. The fee above is separate from it.`)}
${info(`<p>The figures shown are the current values, but the app and the ${doc("api", "API")} read the fee
from the contracts at load rather than hardcoding it. If you are building an integration, do the same —
never cache a fee across sessions.</p>`)}

${h2("Why a flat fee")}
${p(`A percentage fee scales with the size of the position and not with the cost of providing anything.
It also creates a bad incentive: a locker paid in your token has a reason to prefer larger locks over
appropriate ones. A flat fee in ETH costs the same to lock a treasury as to lock a test balance, and the
contracts never take custody of a percentage of anything.`)}

${h2("Overpayment")}
${table(["Contract", "Behaviour"], [
  ["Locker", "Accepts more than the fee and <b>refunds the difference</b>"],
  ["Burner", "Accepts more than the fee and <b>refunds the difference</b>"],
  ["Vesting", "Requires <code>msg.value == fee</code> <b>exactly</b>. No refund path"],
])}
${warn(`<p>The vesting contract's exact-fee rule is the one asymmetry worth remembering when you build a
transaction by hand. Read the fee immediately before sending rather than reusing a value from earlier in
the session. Batch creation requires <code>fee × n</code>, again exactly.</p>`)}

${h2("Can the fee change?")}
${p(`Yes, and only for new records. An existing lock or schedule is never re-priced, and withdrawal and
claiming stay free regardless.`)}
${ul([
  "<b>Vesting has a hard cap of 0.05 ETH</b> written into the contract as a constant. No admin action can exceed it.",
  "<b>The locker and burner have no such cap.</b> The admin can set any fee for new records. Existing locks are unaffected, but it is a real difference and worth knowing rather than discovering.",
])}
${p(`The exact functions are listed on the ${doc("contracts", "contract reference")}, and what admin can
and cannot reach is covered in the ${doc("security", "security model")}.`)}

${h2("What the fee does not buy")}
${p(`It is worth being explicit: the fee pays for creating a record and hosting the proof page. It is not
an audit, an endorsement or a review. A locked token is a token with a locked balance —
${blog("rug-pull-red-flags-checklist", "everything else still needs checking")}.`)}

${h2("For partners")}
${p(`Teams that integrate the ${doc("embed", "embed widget")} or the ${doc("api", "REST API")} earn
<b>50%</b> of the fee on every action generated by a wallet they introduced, claimable to their own wallet
once the balance passes $10.`)}
`,
  related: [
    { href: "/docs/contracts", title: "Contracts", note: "where the fee lives" },
    { href: "/docs/security", title: "Security model" },
    { href: "/docs/embed", title: "Embed widget", note: "earn half the fee" },
  ],
};
